services:
  sim-frontend:
    build: .
    ports:
      - "4002:4002"
    volumes:
      - /home/sav2748/ssl:/sim/ssl:ro  # Mount SSL directory to the container folder
    command: ["npx", "http-server", "./build", "-p", "4002", "--ssl", "--cert", "/sim/ssl/cloudflare-origin.pem", "--key", "/sim/ssl/cloudflare-origin.key"]